# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=400)),
                ('guest_phone', models.IntegerField()),
                ('guest_email', models.EmailField(max_length=254)),
                ('host_name', models.CharField(max_length=400)),
                ('host_phone', models.IntegerField()),
                ('host_email', models.EmailField(max_length=254)),
                ('checkout', models.BooleanField(default=False)),
            ],
        ),
    ]
