# Generated by Django 2.2.7 on 2019-12-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
